### ISSUE TITLE
Incorrect s3fs API call when cleaning up in case of failure

### ISSUE THREAD

**Issue by QuentinMaz** [minrk/kbatch-papermill#1]
Hi,

When I tried to run the [papermill notebook](https://github.com/destination-earth/DestinE_ESA_GFTS/blob/main/docs/papermill_launcher.ipynb), the following error was raised:

```
    154 except Exception:
    155     # cleanup s3 if it fails
    156     s3 = s3fs.S3FileSystem(anon=False)
--> 157     s3.remove(s3_code_url)
    158     raise
    159 return kubernetes_job["metadata"]["name"]

AttributeError: 'S3FileSystem' object has no attribute 'remove'
``` 

I checked the s3fs's documentation and I think a fix would be just to use the correct API:

```
# s3.remove(s3_code_url)
s3.rm(s3_code_url)
```

_(since I am not a collaborator, I can't do the fix / PR myself.)_

**Comment by minrk** [comment]
Thanks for catching this!

> since I am not a collaborator, I can't do the fix / PR myself.

Anyone with a GitHub account can submit a PR to any repo, if you want to give it a shot. You can follow the steps [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) and feel free to ask if you need any help.
